version: '3.4'

services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      DBServer: "db"
      DBPort: "1433"
      DBUser: "SA"
      DBPassword: "Secret_dbpass69"
      Database: "MovieAPI"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "CertPass123"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/API.pfx"
    volumes:
      - ./https/API.pfx:/https/API.pfx:ro
    depends_on:
      - db
    restart: always
    entrypoint: ["./wait-for-it.sh", "db:1433", "-t", "30", "--", "dotnet", "API.dll"]
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Secret_dbpass69"
      MSSQL_PID : Developer
    expose:
      - "1433"
    ports:
      - "1433:1433"
    restart: always